# Preprocessing Demo - placement.csv

**Steps**
1. Load and look
2. Separate numeric and categorical columns
3. Split into X and y
4. Handle missing values
5. Encode categorical columns
6. Scale numeric columns
7. Do 5 and 6 together with ColumnTransformer

**Target shape at the end: (550, 14)**

---
## Step 1 - Load and look

In [ ]:
import  numpy as np
import pandas as pd 


In [2]:
df = pd.read_csv("/Users/snehayadav/Desktop/Assign.Python/placement.csv")

In [3]:
df.info()


<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   student_id           550 non-null    str    
 1   cgpa                 550 non-null    float64
 2   twelfth_percent      550 non-null    float64
 3   branch               550 non-null    str    
 4   internships          519 non-null    float64
 5   projects             550 non-null    int64  
 6   backlogs             550 non-null    int64  
 7   prep_hours           454 non-null    float64
 8   communication_score  538 non-null    float64
 9   hostel               550 non-null    str    
 10  placed               550 non-null    str    
 11  package_lpa          517 non-null    float64
dtypes: float64(6), int64(2), str(4)
memory usage: 51.7 KB


In [5]:
df.describe().columns

Index(['cgpa', 'twelfth_percent', 'internships', 'projects', 'backlogs',
       'prep_hours', 'communication_score', 'package_lpa'],
      dtype='str')

---
## Step 2 - Separate numeric and categorical columns

In [7]:
nums_col= ['cgpa', 'twelfth_percent', 'internships', 'projects', 'backlogs',
       'prep_hours', 'communication_score']
cat_col=['branch','hostel']

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   student_id           550 non-null    str    
 1   cgpa                 550 non-null    float64
 2   twelfth_percent      550 non-null    float64
 3   branch               550 non-null    str    
 4   internships          519 non-null    float64
 5   projects             550 non-null    int64  
 6   backlogs             550 non-null    int64  
 7   prep_hours           454 non-null    float64
 8   communication_score  538 non-null    float64
 9   hostel               550 non-null    str    
 10  placed               550 non-null    str    
 11  package_lpa          517 non-null    float64
dtypes: float64(6), int64(2), str(4)
memory usage: 51.7 KB


---
## Step 3 - Split into X and y

In [9]:
x = df.drop(columns=['student_id','placed','package_lpa'])
y = df['placed']

In [11]:
for col in nums_col:
    df[col] = df[col].fillna(df[col].mean())

---
## Step 4 - Handle missing values

In [10]:
df.isnull().sum()

student_id              0
cgpa                    0
twelfth_percent         0
branch                  0
internships            31
projects                0
backlogs                0
prep_hours             96
communication_score    12
hostel                  0
placed                  0
package_lpa            33
dtype: int64

In [12]:
print(cat_col)

['branch', 'hostel']


In [13]:
df['branch'].value_counts()

branch
CSE      167
IT       118
ECE      112
Mech     103
Civil     50
Name: count, dtype: int64

In [14]:
df['hostel'].value_counts()

hostel
Yes    317
No     233
Name: count, dtype: int64

---
## Step 5 - Encode categorical columns

In [26]:
from sklearn.preprocessing import OneHotEncoder 

In [27]:
cat_col = "branch"

In [28]:
encoder = OneHotEncoder(sparse_output=False)

In [29]:
encoded = encoder.fit_transform(df[[cat_col]])

In [30]:
print(encoded.shape)
print(encoded)

(550, 5)
[[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]


---
## Step 6 - Scale numeric columns

---
## Step 7 - Both together with ColumnTransformer